# EDA: Cirurgia

In [25]:
import pandas as pd

In [26]:
cirurgia_texto = pd.read_csv('../data/raw/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8', dtype=str)
cirurgia_texto.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025/12,CIRURGIA VASCULAR/GERAL,6854,67,102.3,0
1,2023/10,GINECOLOGIA/GERAL,212,5,42.4,0
2,2025/09,UROLOGIA/8,4638,19,244.11,0
3,2024/11,GINECOLOGIA/2,349,6,58.17,0
4,2025/05,GINECOLOGIA/GERAL,18220,108,168.7,0

In [27]:
cirurgia = pd.read_csv('../data/raw/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8')
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025/12,CIRURGIA VASCULAR/GERAL,6854,67,102.30,0
1,2023/10,GINECOLOGIA/GERAL,212,5,42.40,0
2,2025/09,UROLOGIA/8,4638,19,244.11,0
3,2024/11,GINECOLOGIA/2,349,6,58.17,0
4,2025/05,GINECOLOGIA/GERAL,18220,108,168.70,0

In [28]:
pd.concat([cirurgia_texto.dtypes, cirurgia.dtypes], axis=1, keys=['texto', 'inferido'])

                             texto inferido
Mês                            str      str
Especialidade                  str      str
Dias em fila                   str    int64
Em fila                        str    int64
Tempo médio de espera (Dias)   str  float64
Procedimentos realizados       str    int64

In [29]:
cirurgia['Procedimentos realizados'].unique()

array([   0,  487,  931,   21,   28,   13,   18,    8,   15,   38,   41,
         23,   30,    3,   35,    1,  454, 1134,  100,   42,    9, 1231,
         24,    6,    7,  148, 1040,  190, 1168,   11,   17,   19,   98,
       1192,  461,  829,  105,   31,   26, 1029,  351,   45,  273,  107,
        112,  225,   29,    2,  124,  501, 1223,  429,  154, 1112,   36,
        130, 1051,   20,  103,   48,  220,  500,    4,  186,   33, 1413,
        128,  386,  311,  126,   34,  183, 1156,   22,  142,   12,    5,
       1394,   14,  144,  438,  117, 1446,  127,  575,  278, 1034,  119,
        400,  147, 1144,   44,  109,  172,  452,  468,  167,  320,  104,
        141,   40,  181,   27,  149,  212,  125,  382,  621,   85, 1211,
         25,   88,  448,   53, 1340, 1158,  483, 1372,  138,  229,  395,
        475, 1079,   39,  630, 1169,   10,   82,  405,  741,   76, 1129,
         46,  129,  482,   63,  155,  151,   93,  116,  256,  415, 1189,
       1263,  136,  203,   16,  160,  161,  166,  318,   32, 1124, 1172,
        207,   95,  115,  459,  131,  153,   67,   43, 1205,  140, 1061,
        370,  974,  235, 1098,  106,  162,   87,   59,  561,  146,  113,
       1219,   51, 1252,  379,  377, 1277,  435,  867,  224,  110,  410,
        174,  427,  324,  120, 1006,  409,  171,  165,  456,   37,  304,
       1648,  968,  296,  451, 1066,  238, 1495,  962,   89,   72,   83,
       1154, 1045,  191,  982, 1246,  984,  133,  179,  152,  323,  244,
        362, 1111, 1031,  529, 1454,   79,  588,  169,  346,  101,  232,
       1214,  289,   81,  443,  424, 1056,  202,  777,  187,  447,  583,
        584, 1003, 1159,  227,  173, 1110, 1215,  114,  139,   52,  994,
        401, 1142,   99,   57, 1213,  464,  587, 1025,  366,  403,   47,
         49,  905,  917, 1113,  406,  359,  887,  513,  222, 1063,  307,
        534,  121,  682,  163,  981, 1145,  312,  159,  921,  399,  425,
        356, 1148, 1090,  300, 1181, 1117,   80,  927, 1059, 1137,  525,
        949,  168,  497, 1028,   56,  462,  393,  178,  180,  111,  884,
       1115, 1038, 1535,  440,  249, 1139,  387,  460,  322,  423, 1092,
        145,  317,   71,   92,  150, 1187, 1017,  384,  193])

In [30]:
cirurgia[cirurgia['Procedimentos realizados'] > 0]
# 877 linhas com dados. Aparentemente, 0 é a regra.

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
9,2026/03,GINECOLOGIA,42937,486,88.35,487
16,2024/02,CIRURGIA GERAL,26123,790,33.07,931
24,2026/06,CIRURGIA CARDÍACA - ANGIOPLASTIA,261,21,12.43,21
30,2024/04,PCCO - BARIATRICA,588,29,20.28,28
33,2023/07,PCCO - BARIATRICA,402,14,28.71,13
...,...,...,...,...,...,...
6586,2025/06,CIRURGIA VASCULAR,8682,165,52.62,235
6589,2025/02,COLOPROCTOLOGIA,862,17,50.71,56
6591,2023/10,ONCOLOGIA,904,21,43.05,92
6594,2025/01,CIRURGIA VASCULAR,7037,127,55.41,193
6599,2024/10,BUCOMAXILOFACIAL,62,9,6.89,29

In [31]:
cirurgia['Mês'] = pd.to_datetime(cirurgia['Mês'], format='%Y/%m').dt.to_period('M')
cirurgia.dtypes

Mês                             period[M]
Especialidade                         str
Dias em fila                        int64
Em fila                             int64
Tempo médio de espera (Dias)      float64
Procedimentos realizados            int64
dtype: object

In [33]:
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025-12,CIRURGIA VASCULAR/GERAL,6854,67,102.30,0
1,2023-10,GINECOLOGIA/GERAL,212,5,42.40,0
2,2025-09,UROLOGIA/8,4638,19,244.11,0
3,2024-11,GINECOLOGIA/2,349,6,58.17,0
4,2025-05,GINECOLOGIA/GERAL,18220,108,168.70,0

In [51]:
sorted(cirurgia['Especialidade'].loc[cirurgia['Especialidade'].str.startswith('GINECOLOGIA')].unique())

['GINECOLOGIA',
 'GINECOLOGIA/1',
 'GINECOLOGIA/2',
 'GINECOLOGIA/3',
 'GINECOLOGIA/4',
 'GINECOLOGIA/5',
 'GINECOLOGIA/6',
 'GINECOLOGIA/7',
 'GINECOLOGIA/8',
 'GINECOLOGIA/9',
 'GINECOLOGIA/GERAL',
 'GINECOLOGIA/HISTERECTOMIA',
 'GINECOLOGIA/MUTIRÃO']