# EDA: Cirurgia

In [8]:
import pandas as pd

In [9]:
cirurgia_texto = pd.read_csv('../data/raw/20261006/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8', dtype=str)
cirurgia_texto.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2024/09,ORTOPEDIA/FIXADOR EXTERNO,890,13,68.46,0
1,2025/03,CIRURGIA GERAL/1,58,4,14.5,0
2,2023/11,OTORRINOLARINGOLOGIA/NARIZ 1,604,13,46.46,0
3,2024/03,OFTALMOLOGIA/CATARATA OE,630,147,4.29,0
4,2026/01,CARDIOLOGIA,733,4,183.25,4

In [10]:
cirurgia = pd.read_csv('../data/raw/20261006/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8')
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2024/09,ORTOPEDIA/FIXADOR EXTERNO,890,13,68.46,0
1,2025/03,CIRURGIA GERAL/1,58,4,14.50,0
2,2023/11,OTORRINOLARINGOLOGIA/NARIZ 1,604,13,46.46,0
3,2024/03,OFTALMOLOGIA/CATARATA OE,630,147,4.29,0
4,2026/01,CARDIOLOGIA,733,4,183.25,4

In [11]:
pd.concat([cirurgia_texto.dtypes, cirurgia.dtypes], axis=1, keys=['texto', 'inferido'])

                             texto inferido
Mês                            str      str
Especialidade                  str      str
Dias em fila                   str    int64
Em fila                        str    int64
Tempo médio de espera (Dias)   str  float64
Procedimentos realizados       str    int64

In [12]:
cirurgia['Procedimentos realizados'].unique()

array([   0,    4,  382,  395,    3,  682,  359,   19,   44,   16,    2,
        111,    6,   24,  400,   21, 1115,  884,   40,    5,   12,  513,
         23,  154,  141,  459,  322,   20,   17,    7, 1142,   36,   48,
        126,   22, 1110, 1215,   11,  229,   46, 1040,   26,  166,  278,
         72,  173,   39,  366,  256,    8,   30,  152,   79,   41,  161,
        525,  191,  128,   31,  165,   32,  131,  153,   38,   15, 1139,
        249,  387,  311,    1, 1137,  575,  931,   28,   52,  379,   53,
       1144,  147,  150, 1187,  138,  227,  110,  464,   13,  244,    9,
        500,  235,   14,   10, 1372,  377,  119,   93,  116,   76,   71,
        112,  401,  994,   34,   35, 1246, 1124,  429, 1223,  168,  109,
        124,  127, 1045, 1025, 1031, 1156,  460,   57,  921,   18, 1034,
        905,  981, 1145,  144,  139,   63,  163, 1214,   25, 1134,  454,
        105,  487,  225,  136,   42, 1168, 1029,   29, 1231,  104, 1172,
        115,   95, 1192,  207,  160,   45,  273, 1263,  405,  386, 1446,
       1017,  129,  468,  497,  741,   80,  114,  415, 1394, 1117,   83,
        155,   98,  142,  462,   56,  588,  159, 1028, 1113,  406,  324,
       1051,  448,  435,  101,   49,   47,   81,  135,  224,  162,  179,
        962, 1112,  974,  424,  125,  984,  451,  587,  483,  202, 1056,
         87, 1213,   88,  113, 1219,   51,  362,  829,  181,  130,  100,
        203,  471,  175,   27,  220,  190,  461,  452,  172,  318,  501,
        351,  149,  212,  183,  151,  148, 1189,  171, 1111,  482, 1454,
        427,  174,  145,  304,   37,  117,  438,  238,   59, 1079,  630,
        384, 1169,  867,  103,   33,  186, 1340,  927,  296, 1205, 1211,
        456,   67,  178, 1648,  968, 1066,  529, 1495,   89, 1098,  409,
         85,   82, 1061, 1413,  982,  584,  583,  370,  621,  232,  134,
        475, 1200,  393,   92,  193,  346, 1159,  146,  410, 1129,  561,
        949,  447,  120, 1006, 1059, 1003, 1154,   54,  180,  121,  399,
        534,  187,  317,   43, 1158,  289, 1038, 1535,  356,  917,  443,
        140,  323,  169,  425, 1092, 1148,  133, 1277,  222, 1090, 1252,
       1181,   99,  423,  312, 1063, 1141,  403,  307,  440])

In [13]:
cirurgia[cirurgia['Procedimentos realizados'] > 0]
# 877 linhas com dados. Aparentemente, 0 é a regra.

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
4,2026/01,CARDIOLOGIA,733,4,183.25,4
7,2024/01,UROLOGIA,9033,175,51.62,382
9,2025/06,UROLOGIA,4025,72,55.90,395
16,2023/08,PROGRAMA TRANSEXUALIZADOR,322,3,107.33,3
19,2024/04,GINECOLOGIA,15821,676,23.40,682
...,...,...,...,...,...,...
6718,2025/01,PCCO - BARIATRICA,253,9,28.11,8
6729,2024/07,BUCOMAXILOFACIAL,20,1,20.00,18
6736,2023/07,NEUROCIRURGIA,112,1,112.00,12
6749,2024/10,DERMATOLOGIA,256,18,14.22,18
6753,2023/08,GASTROENTEROLOGIA,91,3,30.33,2

In [14]:
cirurgia['Mês'] = pd.to_datetime(cirurgia['Mês'], format='%Y/%m').dt.to_period('M')
cirurgia.dtypes

Mês                             period[M]
Especialidade                         str
Dias em fila                        int64
Em fila                             int64
Tempo médio de espera (Dias)      float64
Procedimentos realizados            int64
dtype: object

In [15]:
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2024-09,ORTOPEDIA/FIXADOR EXTERNO,890,13,68.46,0
1,2025-03,CIRURGIA GERAL/1,58,4,14.50,0
2,2023-11,OTORRINOLARINGOLOGIA/NARIZ 1,604,13,46.46,0
3,2024-03,OFTALMOLOGIA/CATARATA OE,630,147,4.29,0
4,2026-01,CARDIOLOGIA,733,4,183.25,4

In [16]:
sorted(cirurgia['Especialidade'].loc[cirurgia['Especialidade'].str.startswith('GINECOLOGIA')].unique())

['GINECOLOGIA',
 'GINECOLOGIA/1',
 'GINECOLOGIA/2',
 'GINECOLOGIA/3',
 'GINECOLOGIA/4',
 'GINECOLOGIA/5',
 'GINECOLOGIA/6',
 'GINECOLOGIA/7',
 'GINECOLOGIA/8',
 'GINECOLOGIA/9',
 'GINECOLOGIA/GERAL',
 'GINECOLOGIA/HISTERECTOMIA',
 'GINECOLOGIA/MUTIRÃO']

In [17]:
cirurgia_ginecologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('GINECOLOGIA')]
cirurgia_ginecologia.loc[cirurgia_ginecologia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
1141,2026-09,GINECOLOGIA/9,371,2,185.50,0
1814,2026-09,GINECOLOGIA/GERAL,2382,60,39.70,0
1933,2026-09,GINECOLOGIA/3,2583,7,369.00,0
3277,2026-09,GINECOLOGIA,30888,450,68.64,471
3575,2026-09,GINECOLOGIA/2,51,2,25.50,0
3925,2026-09,GINECOLOGIA/HISTERECTOMIA,716,4,179.00,0
6075,2026-09,GINECOLOGIA/4,89,1,89.00,0
6547,2026-09,GINECOLOGIA/6,449,10,44.90,0

In [18]:
cirurgia_urologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('UROLOGIA')]
cirurgia_urologia.loc[cirurgia_urologia["Mês"] == pd.Period('2025-07', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
414,2025-07,UROLOGIA/GERAL,21678,184,117.82,0
1028,2025-07,UROLOGIA,4478,95,47.14,500
1216,2025-07,UROLOGIA/2,988,8,123.50,0
2228,2025-07,UROLOGIA/5,540,4,135.00,0
2270,2025-07,UROLOGIA/4,100,1,100.00,0
2598,2025-07,UROLOGIA/RETIRADA DE DUPLO J,3482,165,21.10,0
2703,2025-07,UROLOGIA/1,1981,45,44.02,0
3582,2025-07,UROLOGIA/3,5839,22,265.41,0
3939,2025-07,UROLOGIA/7,120,1,120.00,0
4135,2025-07,UROLOGIA/LITIASE,1380,8,172.50,0
5087,2025-07,UROLOGIA/TROCA DE DUPLO J,3045,59,51.61,0
6727,2025-07,UROLOGIA/8,1007,10,100.70,0

In [19]:
cirurgia_oftalmologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('OFTALMOLOGIA')]
cirurgia_oftalmologia.loc[cirurgia_oftalmologia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
1842,2026-09,OFTALMOLOGIA/CATARATA OE,1198,121,9.90,0
2495,2026-09,OFTALMOLOGIA/OE,64515,494,130.60,0
2866,2026-09,OFTALMOLOGIA/AO,3739,26,143.81,0
3205,2026-09,OFTALMOLOGIA/AMBULATORIAL - OE,33844,269,125.81,0
3395,2026-09,OFTALMOLOGIA/AMBULATORIAL - OD,34878,308,113.24,0
4120,2026-09,OFTALMOLOGIA/OD,49509,470,105.34,0
5637,2026-09,OFTALMOLOGIA/HOSPITALAR - OD,6306,16,394.13,0
6106,2026-09,OFTALMOLOGIA/HOSPITALAR - OE,3464,12,288.67,0
6679,2026-09,OFTALMOLOGIA/CATARATA OD,1049,121,8.67,0

In [20]:
cirurgia_ortopedia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('ORTOPEDIA')]
cirurgia_ortopedia.loc[cirurgia_ortopedia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
194,2026-09,ORTOPEDIA/1,730,54,13.52,0
274,2026-09,ORTOPEDIA/PÉ/TORNOZELO,687,36,19.08,0
365,2026-09,ORTOPEDIA/3,70,4,17.50,0
442,2026-09,ORTOPEDIA/10,857,3,285.67,0
446,2026-09,ORTOPEDIA/GERAL,2026,54,37.52,0
1101,2026-09,ORTOPEDIA/COTOVELO,359,4,89.75,0
1114,2026-09,ORTOPEDIA/6,344,3,114.67,0
1125,2026-09,ORTOPEDIA/OMBRO E COTOVELO,107,8,13.38,0
1209,2026-09,ORTOPEDIA/PLEXO BRAQUIAL,229,2,114.50,0
1671,2026-09,ORTOPEDIA/FIXADOR EXTERNO,998,22,45.36,0
2079,2026-09,ORTOPEDIA/RETIRADA DE FIXADOR EXTERNO,419,20,20.95,0
2463,2026-09,ORTOPEDIA/PÉ E TORNOZELO,58,8,7.25,0
2712,2026-09,ORTOPEDIA/PEDIÁTRICA GERAL,1738,21,82.76,0
2713,2026-09,ORTOPEDIA/RETIRADA,314,9,34.89,0
3009,2026-09,ORTOPEDIA/JOELHO,2595,30,86.50,0
3084,2026-09,ORTOPEDIA/COLUNA (BLOQUEIOS),539,9,59.89,0
3879,2026-09,ORTOPEDIA/JOELHO (ARTROSCOPIAS),813,31,26.23,0
3979,2026-09,ORTOPEDIA/4,1737,12,144.75,0
4017,2026-09,ORTOPEDIA/5,16554,16,1034.63,0
4063,2026-09,ORTOPEDIA/8,7053,9,783.67,0
4285,2026-09,ORTOPEDIA/TUMOR,130,5,26.00,0
4344,2026-09,ORTOPEDIA/ARTROPLASTIA,689,1,689.00,0
4441,2026-09,ORTOPEDIA/RETIRADA DE MATERIAL,5186,12,432.17,0
4458,2026-09,ORTOPEDIA/QUADRIL,8587,45,190.82,0
4552,2026-09,ORTOPEDIA/REVISÃO QUADRIL,3477,5,695.40,0
4673,2026-09,ORTOPEDIA/MÃO E PUNHO,58,6,9.67,0
4885,2026-09,ORTOPEDIA/OMBRO,4105,67,61.27,0
5057,2026-09,ORTOPEDIA/MÃO,3845,40,96.13,0
5068,2026-09,ORTOPEDIA/REVISÃO JOELHO,1227,3,409.00,0
5213,2026-09,ORTOPEDIA/COLUNA (DEFORMIDADES),394,3,131.33,0
5232,2026-09,ORTOPEDIA/RETIRADA DE FIO OU PINO,759,16,47.44,0
5409,2026-09,ORTOPEDIA/9,1648,5,329.60,0
5681,2026-09,ORTOPEDIA/RETIRADA DE MATERIAL SÍNTESE,493,33,14.94,0
5712,2026-09,ORTOPEDIA/12,934,1,934.00,0
5891,2026-09,ORTOPEDIA/GERAL E TRAUMATOLOGIA,132,12,11.00,0
5956,2026-09,ORTOPEDIA/2,2676,22,121.64,0
6073,2026-09,ORTOPEDIA/COLUNA (ARTRODESE),2946,13,226.62,0
6471,2026-09,ORTOPEDIA/JOELHO (ATJ),24720,27,915.56,0
6507,2026-09,ORTOPEDIA/7,946,3,315.33,0
6612,2026-09,ORTOPEDIA,72456,719,100.77,1141