# EDA: Cirurgia

In [1]:
import pandas as pd

In [2]:
cirurgia_texto = pd.read_csv('../data/raw/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8', dtype=str)
cirurgia_texto.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025/12,CIRURGIA VASCULAR/GERAL,6854,67,102.3,0
1,2023/10,GINECOLOGIA/GERAL,212,5,42.4,0
2,2025/09,UROLOGIA/8,4638,19,244.11,0
3,2024/11,GINECOLOGIA/2,349,6,58.17,0
4,2025/05,GINECOLOGIA/GERAL,18220,108,168.7,0

In [3]:
cirurgia = pd.read_csv('../data/raw/indicadores-de-cirurgia.csv', sep=';', encoding='utf-8')
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025/12,CIRURGIA VASCULAR/GERAL,6854,67,102.30,0
1,2023/10,GINECOLOGIA/GERAL,212,5,42.40,0
2,2025/09,UROLOGIA/8,4638,19,244.11,0
3,2024/11,GINECOLOGIA/2,349,6,58.17,0
4,2025/05,GINECOLOGIA/GERAL,18220,108,168.70,0

In [4]:
pd.concat([cirurgia_texto.dtypes, cirurgia.dtypes], axis=1, keys=['texto', 'inferido'])

                             texto inferido
Mês                            str      str
Especialidade                  str      str
Dias em fila                   str    int64
Em fila                        str    int64
Tempo médio de espera (Dias)   str  float64
Procedimentos realizados       str    int64

In [5]:
cirurgia['Procedimentos realizados'].unique()

array([   0,  487,  931,   21,   28,   13,   18,    8,   15,   38,   41,
         23,   30,    3,   35,    1,  454, 1134,  100,   42,    9, 1231,
         24,    6,    7,  148, 1040,  190, 1168,   11,   17,   19,   98,
       1192,  461,  829,  105,   31,   26, 1029,  351,   45,  273,  107,
        112,  225,   29,    2,  124,  501, 1223,  429,  154, 1112,   36,
        130, 1051,   20,  103,   48,  220,  500,    4,  186,   33, 1413,
        128,  386,  311,  126,   34,  183, 1156,   22,  142,   12,    5,
       1394,   14,  144,  438,  117, 1446,  127,  575,  278, 1034,  119,
        400,  147, 1144,   44,  109,  172,  452,  468,  167,  320,  104,
        141,   40,  181,   27,  149,  212,  125,  382,  621,   85, 1211,
         25,   88,  448,   53, 1340, 1158,  483, 1372,  138,  229,  395,
        475, 1079,   39,  630, 1169,   10,   82,  405,  741,   76, 1129,
         46,  129,  482,   63,  155,  151,   93,  116,  256,  415, 1189,
       1263,  136,  203,   16,  160,  161,  166,  318,   32, 1124, 1172,
        207,   95,  115,  459,  131,  153,   67,   43, 1205,  140, 1061,
        370,  974,  235, 1098,  106,  162,   87,   59,  561,  146,  113,
       1219,   51, 1252,  379,  377, 1277,  435,  867,  224,  110,  410,
        174,  427,  324,  120, 1006,  409,  171,  165,  456,   37,  304,
       1648,  968,  296,  451, 1066,  238, 1495,  962,   89,   72,   83,
       1154, 1045,  191,  982, 1246,  984,  133,  179,  152,  323,  244,
        362, 1111, 1031,  529, 1454,   79,  588,  169,  346,  101,  232,
       1214,  289,   81,  443,  424, 1056,  202,  777,  187,  447,  583,
        584, 1003, 1159,  227,  173, 1110, 1215,  114,  139,   52,  994,
        401, 1142,   99,   57, 1213,  464,  587, 1025,  366,  403,   47,
         49,  905,  917, 1113,  406,  359,  887,  513,  222, 1063,  307,
        534,  121,  682,  163,  981, 1145,  312,  159,  921,  399,  425,
        356, 1148, 1090,  300, 1181, 1117,   80,  927, 1059, 1137,  525,
        949,  168,  497, 1028,   56,  462,  393,  178,  180,  111,  884,
       1115, 1038, 1535,  440,  249, 1139,  387,  460,  322,  423, 1092,
        145,  317,   71,   92,  150, 1187, 1017,  384,  193])

In [6]:
cirurgia[cirurgia['Procedimentos realizados'] > 0]
# 877 linhas com dados. Aparentemente, 0 é a regra.

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
9,2026/03,GINECOLOGIA,42937,486,88.35,487
16,2024/02,CIRURGIA GERAL,26123,790,33.07,931
24,2026/06,CIRURGIA CARDÍACA - ANGIOPLASTIA,261,21,12.43,21
30,2024/04,PCCO - BARIATRICA,588,29,20.28,28
33,2023/07,PCCO - BARIATRICA,402,14,28.71,13
...,...,...,...,...,...,...
6586,2025/06,CIRURGIA VASCULAR,8682,165,52.62,235
6589,2025/02,COLOPROCTOLOGIA,862,17,50.71,56
6591,2023/10,ONCOLOGIA,904,21,43.05,92
6594,2025/01,CIRURGIA VASCULAR,7037,127,55.41,193
6599,2024/10,BUCOMAXILOFACIAL,62,9,6.89,29

In [7]:
cirurgia['Mês'] = pd.to_datetime(cirurgia['Mês'], format='%Y/%m').dt.to_period('M')
cirurgia.dtypes

Mês                             period[M]
Especialidade                         str
Dias em fila                        int64
Em fila                             int64
Tempo médio de espera (Dias)      float64
Procedimentos realizados            int64
dtype: object

In [8]:
cirurgia.head()

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
0,2025-12,CIRURGIA VASCULAR/GERAL,6854,67,102.30,0
1,2023-10,GINECOLOGIA/GERAL,212,5,42.40,0
2,2025-09,UROLOGIA/8,4638,19,244.11,0
3,2024-11,GINECOLOGIA/2,349,6,58.17,0
4,2025-05,GINECOLOGIA/GERAL,18220,108,168.70,0

In [9]:
sorted(cirurgia['Especialidade'].loc[cirurgia['Especialidade'].str.startswith('GINECOLOGIA')].unique())

['GINECOLOGIA',
 'GINECOLOGIA/1',
 'GINECOLOGIA/2',
 'GINECOLOGIA/3',
 'GINECOLOGIA/4',
 'GINECOLOGIA/5',
 'GINECOLOGIA/6',
 'GINECOLOGIA/7',
 'GINECOLOGIA/8',
 'GINECOLOGIA/9',
 'GINECOLOGIA/GERAL',
 'GINECOLOGIA/HISTERECTOMIA',
 'GINECOLOGIA/MUTIRÃO']

In [18]:
cirurgia_ginecologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('GINECOLOGIA')]
cirurgia_ginecologia.loc[cirurgia_ginecologia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
11,2026-09,GINECOLOGIA/GERAL,7751,135,57.41,0
143,2026-09,GINECOLOGIA/3,17326,78,222.13,0
764,2026-09,GINECOLOGIA/HISTERECTOMIA,8913,77,115.75,0
1032,2026-09,GINECOLOGIA,318044,1910,166.52,320
1505,2026-09,GINECOLOGIA/2,1065,9,118.33,0
1871,2026-09,GINECOLOGIA/9,34952,108,323.63,0
3509,2026-09,GINECOLOGIA/6,1811,48,37.73,0
3741,2026-09,GINECOLOGIA/8,30,1,30.00,0
3926,2026-09,GINECOLOGIA/4,1117,6,186.17,0
6598,2026-09,GINECOLOGIA/1,226,2,113.00,0

In [22]:
cirurgia_urologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('UROLOGIA')]
cirurgia_urologia.loc[cirurgia_urologia["Mês"] == pd.Period('2025-07', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
931,2025-07,UROLOGIA/RETIRADA DE DUPLO J,3482,165,21.10,0
1373,2025-07,UROLOGIA/7,120,1,120.00,0
1712,2025-07,UROLOGIA/GERAL,21678,184,117.82,0
2102,2025-07,UROLOGIA/5,540,4,135.00,0
2150,2025-07,UROLOGIA/4,100,1,100.00,0
2207,2025-07,UROLOGIA/LITIASE,1380,8,172.50,0
3549,2025-07,UROLOGIA/3,5839,22,265.41,0
4182,2025-07,UROLOGIA/2,988,8,123.50,0
4382,2025-07,UROLOGIA,4478,95,47.14,500
4827,2025-07,UROLOGIA/8,1007,10,100.70,0
5782,2025-07,UROLOGIA/1,1981,45,44.02,0
6473,2025-07,UROLOGIA/TROCA DE DUPLO J,3045,59,51.61,0

In [24]:
cirurgia_oftalmologia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('OFTALMOLOGIA')]
cirurgia_oftalmologia.loc[cirurgia_oftalmologia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
782,2026-09,OFTALMOLOGIA/CATARATA OE,2665,125,21.32,0
935,2026-09,OFTALMOLOGIA/AMBULATORIAL - OE,207450,1326,156.45,0
1239,2026-09,OFTALMOLOGIA/AMBULATORIAL - OD,197375,1226,160.99,0
2460,2026-09,OFTALMOLOGIA/OE,285026,2811,101.40,0
3210,2026-09,OFTALMOLOGIA/AO,120358,499,241.20,0
3801,2026-09,OFTALMOLOGIA/HOSPITALAR - OE,50118,175,286.39,0
4635,2026-09,OFTALMOLOGIA/HOSPITALAR - OD,51909,172,301.80,0
4907,2026-09,OFTALMOLOGIA/CATARATA OD,2516,125,20.13,0
6364,2026-09,OFTALMOLOGIA/OD,229236,2472,92.73,0

In [25]:
cirurgia_ortopedia = cirurgia.loc[cirurgia['Especialidade'].str.startswith('ORTOPEDIA')]
cirurgia_ortopedia.loc[cirurgia_ortopedia["Mês"] == pd.Period('2026-09', 'M')]

,Mês,Especialidade,Dias em fila,Em fila,Tempo médio de espera (Dias),Procedimentos realizados
32,2026-09,ORTOPEDIA/PLEXO BRAQUIAL,3688,15,245.87,0
215,2026-09,ORTOPEDIA/COTOVELO,5082,19,267.47,0
710,2026-09,ORTOPEDIA/1,1750,68,25.74,0
877,2026-09,ORTOPEDIA/OMBRO E COTOVELO,103,8,12.88,0
950,2026-09,ORTOPEDIA/MÃO E PUNHO,56,6,9.33,0
999,2026-09,ORTOPEDIA/JOELHO,77375,222,348.54,0
1263,2026-09,ORTOPEDIA/13,1256,1,1256.00,0
1384,2026-09,ORTOPEDIA/JOELHO (ARTROSCOPIAS),4688,89,52.67,0
1431,2026-09,ORTOPEDIA/6,1413,11,128.45,0
1781,2026-09,ORTOPEDIA/RETIRADA DE FIXADOR EXTERNO,471,27,17.44,0
2013,2026-09,ORTOPEDIA/OMBRO (ARTROPLASTIAS),59382,79,751.67,0
2341,2026-09,ORTOPEDIA/QUADRIL PEDIÁTRICA,7213,26,277.42,0
2723,2026-09,ORTOPEDIA/RETIRADA,3863,42,91.98,0
2724,2026-09,ORTOPEDIA/PEDIÁTRICA GERAL,8563,93,92.08,0
2826,2026-09,ORTOPEDIA/8,95363,234,407.53,0
2959,2026-09,ORTOPEDIA/TUMOR,560,8,70.00,0
3045,2026-09,ORTOPEDIA/MÃO,114814,395,290.67,0
3256,2026-09,ORTOPEDIA/11,19960,26,767.69,0
3435,2026-09,ORTOPEDIA/QUADRIL,69110,244,283.24,0
3562,2026-09,ORTOPEDIA/3,6217,24,259.04,0
3758,2026-09,ORTOPEDIA/GERAL E TRAUMATOLOGIA,156,14,11.14,0
3871,2026-09,ORTOPEDIA/COLUNA (BLOQUEIOS),1411,31,45.52,0
3896,2026-09,ORTOPEDIA,675932,2318,291.60,777
3925,2026-09,ORTOPEDIA/COLUNA (ARTRODESE),46276,200,231.38,0
4049,2026-09,ORTOPEDIA/RETIRADA DE MATERIAL,75928,232,327.28,0
4153,2026-09,ORTOPEDIA/PÉ/TORNOZELO,70734,214,330.53,0
4330,2026-09,ORTOPEDIA/5,71502,120,595.85,0
4356,2026-09,ORTOPEDIA/RETIRADA DE MATERIAL SÍNTESE,2686,47,57.15,0
4398,2026-09,ORTOPEDIA/REVISÃO QUADRIL,174230,272,640.55,0
4645,2026-09,ORTOPEDIA/4,4263,28,152.25,0
4718,2026-09,ORTOPEDIA/7,13562,33,410.97,0
4760,2026-09,ORTOPEDIA/12,7937,13,610.54,0
4845,2026-09,ORTOPEDIA/JOELHO (ATJ),882516,1323,667.06,0
4998,2026-09,ORTOPEDIA/RETIRADA DE FIO OU PINO,1099,18,61.06,0
5031,2026-09,ORTOPEDIA/COLUNA (DEFORMIDADES),51954,115,451.77,0
5094,2026-09,ORTOPEDIA/10,29889,72,415.13,0
5095,2026-09,ORTOPEDIA/GERAL,135595,403,336.46,0
5160,2026-09,ORTOPEDIA/REVISÃO JOELHO,59886,86,696.35,0
5190,2026-09,ORTOPEDIA/PÉ E TORNOZELO,58,8,7.25,0
5338,2026-09,ORTOPEDIA/FIXADOR EXTERNO,45308,153,296.13,0
5542,2026-09,ORTOPEDIA/9,40405,146,276.75,0
6140,2026-09,ORTOPEDIA/OMBRO,115331,420,274.60,0
6197,2026-09,ORTOPEDIA/2,9177,58,158.22,0
6470,2026-09,ORTOPEDIA/ARTROPLASTIA,105085,179,587.07,0