# EDA: Consultas

In [1]:
import pandas as pd

In [2]:
consulta_texto = pd.read_csv('../data/raw/20261006/indicadores-de-consulta.csv', sep=';', encoding='utf-8', dtype=str)
consulta_texto.head()

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Especialidade,Sub-Especialidade,Complexidade,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
0,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,2535939 / HOSPITAL SAO COTTOLENGO,CENTRAL,ONCOLOGIA CLINICA,ONCOLOGIA CLINICA UROLOGIA,ALTA,8.0,8.0,100.0,0,100.0,0.0,0,0.0,0.0,0.0
1,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,2855356 / POLICLINICA ESTADUAL BRASIL BRUNO DE...,RIO VERMELHO,CARDIOLOGIA,CARDIOLOGIA PEDIÁTRICA,ALTA,11.0,11.0,100.0,0,100.0,0.0,0,0.0,0.0,0.0
2,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,7743068 / HOSPITAL ESTADUAL DE URGENCIAS GOV O...,CENTRAL,CARDIOLOGIA,(INATIVO)CARDIOLOGIA ADULTO,ALTA,10.0,10.0,100.0,0,100.0,0.0,0,0.0,0.0,0.0
3,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,7743068 / HOSPITAL ESTADUAL DE URGENCIAS GOV O...,CENTRAL,PNEUMOLOGIA,PNEUMOLOGIA GERAL,ALTA,24.0,24.0,100.0,2,91.67,0.0,0,0.0,0.0,0.0
4,2023/11,COMPLEXO REGULADOR ESTADUAL CRE,2535939 / HOSPITAL SAO COTTOLENGO,CENTRAL,ONCOLOGIA CLINICA,ONCOLOGIA CLINICA UROLOGIA,ALTA,22.0,22.0,100.0,1,95.45,0.0,0,0.0,0.0,0.0

In [3]:
consulta = pd.read_csv('../data/raw/20261006/indicadores-de-consulta.csv', sep=';', encoding='utf-8')
consulta.head()

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Especialidade,Sub-Especialidade,Complexidade,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
0,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,2535939 / HOSPITAL SAO COTTOLENGO,CENTRAL,ONCOLOGIA CLINICA,ONCOLOGIA CLINICA UROLOGIA,ALTA,8.0,8.0,100.0,0,100.00,0.0,0,0.0,0.0,0.0
1,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,2855356 / POLICLINICA ESTADUAL BRASIL BRUNO DE...,RIO VERMELHO,CARDIOLOGIA,CARDIOLOGIA PEDIÁTRICA,ALTA,11.0,11.0,100.0,0,100.00,0.0,0,0.0,0.0,0.0
2,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,7743068 / HOSPITAL ESTADUAL DE URGENCIAS GOV O...,CENTRAL,CARDIOLOGIA,(INATIVO)CARDIOLOGIA ADULTO,ALTA,10.0,10.0,100.0,0,100.00,0.0,0,0.0,0.0,0.0
3,2023/10,COMPLEXO REGULADOR ESTADUAL CRE,7743068 / HOSPITAL ESTADUAL DE URGENCIAS GOV O...,CENTRAL,PNEUMOLOGIA,PNEUMOLOGIA GERAL,ALTA,24.0,24.0,100.0,2,91.67,0.0,0,0.0,0.0,0.0
4,2023/11,COMPLEXO REGULADOR ESTADUAL CRE,2535939 / HOSPITAL SAO COTTOLENGO,CENTRAL,ONCOLOGIA CLINICA,ONCOLOGIA CLINICA UROLOGIA,ALTA,22.0,22.0,100.0,1,95.45,0.0,0,0.0,0.0,0.0

In [4]:
pd.concat([consulta_texto.dtypes, consulta.dtypes], axis=1, keys=['texto', 'inferido'])

                                                   texto inferido
Mês                                                  str      str
Central Regulação                                    str      str
Unidade de saúde                                     str      str
Unidade de saúde/Região                              str      str
Especialidade                                        str      str
Sub-Especialidade                                    str      str
Complexidade                                         str      str
Vagas ofertadas                                      str  float64
Vagas não preenchidas                                str  float64
Perda primária                                       str  float64
Agendamentos cancelados pelo solicitante ou rot...   str    int64
Perda primária sem cancelamentos                     str  float64
Agendamentos                                         str  float64
Compareceu                                           str    int64
Faltantes                                            str  float64
Perda secundária                                     str  float64
Tempo médio de espera (Dias)                         str  float64

In [5]:
consulta['Mês'] = pd.to_datetime(consulta['Mês'], format='%Y/%m').dt.to_period('M')
consulta.dtypes

Mês                                                              period[M]
Central Regulação                                                      str
Unidade de saúde                                                       str
Unidade de saúde/Região                                                str
Especialidade                                                          str
Sub-Especialidade                                                      str
Complexidade                                                           str
Vagas ofertadas                                                    float64
Vagas não preenchidas                                              float64
Perda primária                                                     float64
Agendamentos cancelados pelo solicitante ou rotina automática        int64
Perda primária sem cancelamentos                                   float64
Agendamentos                                                       float64
Compareceu                                                           int64
Faltantes                                                          float64
Perda secundária                                                   float64
Tempo médio de espera (Dias)                                       float64
dtype: object

In [6]:
consulta.loc[consulta["Mês"] == pd.Period('2026-08', 'M')]

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Especialidade,Sub-Especialidade,Complexidade,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
14080,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,107387 / CLINICA DO RIM,SUDOESTE I,UROLOGIA,UROLOGIA GERAL,ALTA,41.0,0.0,0.00,0,0.0,40.0,32,8.0,20.00,5.10
14081,2026-08,CENTRAL DE REGULACAO DE PORANGATU,110140 / CENTRO DE ESPECIALIDADE MEDICAS,NORTE,CARDIOLOGIA,CARDIOLOGIA GERAL,MEDIA,91.0,0.0,0.00,0,0.0,91.0,82,8.0,8.79,38.82
14082,2026-08,CENTRAL DE REGULACAO DE PORANGATU,110140 / CENTRO DE ESPECIALIDADE MEDICAS,NORTE,CIRURGIA,CIRURGIA GERAL,MEDIA,50.0,0.0,0.00,0,0.0,49.0,45,4.0,8.16,18.76
14083,2026-08,CENTRAL DE REGULACAO DE PORANGATU,110140 / CENTRO DE ESPECIALIDADE MEDICAS,NORTE,GINECOLOGIA,GINECOLOGIA GERAL,MEDIA,12.0,1.0,8.33,1,0.0,11.0,5,6.0,54.55,53.43
14084,2026-08,CENTRAL DE REGULACAO DE PORANGATU,110140 / CENTRO DE ESPECIALIDADE MEDICAS,NORTE,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA GERAL,MEDIA,100.0,3.0,3.00,3,0.0,97.0,71,14.0,14.43,4.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14919,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,9916466 / INSTITUTO DE COLUNA VERTEBRAL DE RIO...,SUDOESTE I,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA GERAL,ALTA,299.0,0.0,0.00,0,0.0,223.0,13,5.0,2.24,22.82
14920,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,9916466 / INSTITUTO DE COLUNA VERTEBRAL DE RIO...,SUDOESTE I,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA JOELHO,ALTA,180.0,1.0,0.56,1,0.0,138.0,128,10.0,7.25,10.91
14921,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,9916466 / INSTITUTO DE COLUNA VERTEBRAL DE RIO...,SUDOESTE I,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA OMBRO E COTOVELO,ALTA,59.0,0.0,0.00,0,0.0,47.0,41,6.0,12.77,82.93
14922,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,9916466 / INSTITUTO DE COLUNA VERTEBRAL DE RIO...,SUDOESTE I,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA PÉ E TORNOZELO,ALTA,42.0,0.0,0.00,0,0.0,42.0,38,0.0,0.00,11.49
14923,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,9916466 / INSTITUTO DE COLUNA VERTEBRAL DE RIO...,SUDOESTE I,ORTOPEDIA E TRAUMATOLOGIA,ORTOPEDIA E TRAUMATOLOGIA QUADRIL,ALTA,25.0,12.0,48.00,12,0.0,11.0,9,2.0,18.18,12.29