# EDA: Exames

In [1]:
import pandas as pd

In [2]:
exame_texto = pd.read_csv('../data/raw/20261006/indicadores-de-exames.csv', sep=';', encoding='utf-8', dtype=str)
exame_texto.head()

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Grupo de exames,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
0,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,COLONOSCOPIA,90.0,27.0,30.0,0,30.0,63.0,0,63.0,100.0,74.0
1,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ELETROCARDIOGRAMA,228.0,212.0,92.98,0,92.98,16.0,0,16.0,100.0,0.0
2,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ENDOSCOPIA DIGESTIVA ALTA,116.0,56.0,48.28,0,48.28,60.0,1,59.0,98.33,366.33
3,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,RADIOGRAFIA,1110.0,1110.0,100.0,0,100.0,0.0,0,0.0,0.0,0.0
4,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ULTRASSONOGRAFIA,89.0,73.0,82.02,0,82.02,16.0,0,16.0,100.0,0.0

In [4]:
exame = pd.read_csv('../data/raw/20261006/indicadores-de-exames.csv', sep=';', encoding='utf-8')
exame.head()

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Grupo de exames,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
0,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,COLONOSCOPIA,90.0,27.0,30.00,0,30.00,63.0,0,63.0,100.00,74.00
1,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ELETROCARDIOGRAMA,228.0,212.0,92.98,0,92.98,16.0,0,16.0,100.00,0.00
2,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ENDOSCOPIA DIGESTIVA ALTA,116.0,56.0,48.28,0,48.28,60.0,1,59.0,98.33,366.33
3,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,RADIOGRAFIA,1110.0,1110.0,100.00,0,100.00,0.0,0,0.0,0.00,0.00
4,2024/11,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ULTRASSONOGRAFIA,89.0,73.0,82.02,0,82.02,16.0,0,16.0,100.00,0.00

In [5]:
pd.concat([exame_texto.dtypes, exame.dtypes], axis=1, keys=['texto', 'inferido'])

                                                   texto inferido
Mês                                                  str      str
Central Regulação                                    str      str
Unidade de saúde                                     str      str
Unidade de saúde/Região                              str      str
Grupo de exames                                      str      str
Vagas ofertadas                                      str  float64
Vagas não preenchidas                                str  float64
Perda primária                                       str  float64
Agendamentos cancelados pelo solicitante ou rot...   str    int64
Perda primária sem cancelamentos                     str  float64
Agendamentos                                         str  float64
Compareceu                                           str    int64
Faltantes                                            str  float64
Perda secundária                                     str  float64
Tempo médio de espera (Dias)                         str  float64

In [6]:
exame['Mês'] = pd.to_datetime(exame['Mês'], format='%Y/%m').dt.to_period('M')
exame.dtypes

Mês                                                              period[M]
Central Regulação                                                      str
Unidade de saúde                                                       str
Unidade de saúde/Região                                                str
Grupo de exames                                                        str
Vagas ofertadas                                                    float64
Vagas não preenchidas                                              float64
Perda primária                                                     float64
Agendamentos cancelados pelo solicitante ou rotina automática        int64
Perda primária sem cancelamentos                                   float64
Agendamentos                                                       float64
Compareceu                                                           int64
Faltantes                                                          float64
Perda secundária                                                   float64
Tempo médio de espera (Dias)                                       float64
dtype: object

In [7]:
exame.loc[exame["Mês"] == pd.Period('2026-08', 'M')]

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Grupo de exames,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
7512,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,211354 / DAMASCENO MARTINS HOME CARE LTDA,SUDOESTE I,ECOCARDIOGRAFIA TRANSTORACICA,268.0,7.0,2.61,7,0.00,207.0,183,22.0,10.63,35.80
7513,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,COLONOSCOPIA,33.0,0.0,0.00,0,0.00,33.0,3,11.0,33.33,288.62
7514,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,DOPPLER,52.0,0.0,0.00,0,0.00,52.0,11,14.0,26.92,65.48
7515,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,ENDOSCOPIA DIGESTIVA ALTA,25.0,0.0,0.00,0,0.00,25.0,3,11.0,44.00,228.73
7516,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,2338262 / HOSPITAL DE URGENCIAS DE GOIAS DR VA...,CENTRAL,TOMOGRAFIA COMPUTADORIZADA (SEM SEDAÇÃO),126.0,0.0,0.00,0,0.00,126.0,17,41.0,32.54,22.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7987,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,965324 / HOSPITAL ESTADUAL DA CRIANCA E DO ADO...,CENTRAL,RADIOGRAFIA,21.0,2.0,9.52,0,9.52,19.0,10,8.0,42.11,1.91
7988,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,965324 / HOSPITAL ESTADUAL DA CRIANCA E DO ADO...,CENTRAL,TOMOGRAFIA COMPUTADORIZADA (COM SEDAÇÃO),4.0,0.0,0.00,0,0.00,4.0,1,2.0,50.00,318.50
7989,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,965324 / HOSPITAL ESTADUAL DA CRIANCA E DO ADO...,CENTRAL,TOMOGRAFIA COMPUTADORIZADA (SEM SEDAÇÃO),9.0,0.0,0.00,0,0.00,9.0,5,2.0,22.22,21.67
7990,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,965324 / HOSPITAL ESTADUAL DA CRIANCA E DO ADO...,CENTRAL,ULTRASSONOGRAFIA,4.0,0.0,0.00,0,0.00,4.0,1,3.0,75.00,236.75
7991,2026-08,CENTRAL DE REGULACAO DE INHUMAS,9814035 / LAB CLIN,CENTRAL,ANÁLISES CLÍNICAS,630.0,396.0,62.86,20,59.68,234.0,186,48.0,20.51,4.92

In [9]:
exame.loc[(exame["Mês"].dt.year == 2026) & (exame["Grupo de exames"] == "POLISSONOGRAFIA")]

,Mês,Central Regulação,Unidade de saúde,Unidade de saúde/Região,Grupo de exames,Vagas ofertadas,Vagas não preenchidas,Perda primária,Agendamentos cancelados pelo solicitante ou rotina automática,Perda primária sem cancelamentos,Agendamentos,Compareceu,Faltantes,Perda secundária,Tempo médio de espera (Dias)
4411,2026-01,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,52.0,1.0,1.92,1,0.00,51.0,33,18.0,35.29,232.79
4780,2026-01,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,6.0,4.0,66.67,0,66.67,2.0,2,0.0,0.00,75.00
4834,2026-02,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,52.0,0.0,0.00,0,0.00,52.0,34,18.0,34.62,235.18
5210,2026-02,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,6.0,2.0,33.33,0,33.33,4.0,3,1.0,25.00,139.83
5263,2026-03,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,52.0,2.0,3.85,2,0.00,50.0,35,15.0,30.00,259.07
5645,2026-03,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,11.0,1.0,9.09,0,9.09,10.0,9,1.0,10.00,169.75
5701,2026-04,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,52.0,1.0,1.92,1,0.00,51.0,27,24.0,47.06,87.59
6086,2026-04,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,7.0,1.0,14.29,1,0.00,6.0,3,3.0,50.00,208.00
6147,2026-05,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,24.0,0.0,0.00,0,0.00,24.0,13,11.0,45.83,0.00
6550,2026-05,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,11.0,2.0,18.18,2,0.00,9.0,9,0.0,0.00,215.33
6611,2026-06,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,15.0,0.0,0.00,0,0.00,15.0,7,8.0,53.33,119.67
7020,2026-06,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,12.0,2.0,16.67,2,0.00,8.0,6,2.0,25.00,259.25
7077,2026-07,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,25.0,0.0,0.00,0,0.00,25.0,18,7.0,28.00,224.83
7482,2026-07,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,9.0,0.0,0.00,0,0.00,8.0,6,2.0,25.00,193.00
7537,2026-08,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,20.0,0.0,0.00,0,0.00,20.0,14,6.0,30.00,158.06
7951,2026-08,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,25.0,2.0,8.00,2,0.00,21.0,17,4.0,19.05,347.11
8018,2026-09,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,20.0,0.0,0.00,0,0.00,20.0,13,7.0,35.00,142.55
8453,2026-09,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,78.0,4.0,5.13,4,0.00,72.0,61,11.0,15.28,289.25
8522,2026-10,COMPLEXO REGULADOR ESTADUAL CRE,2338734 / HOSPITAL ESTADUAL DR ALBERTO RASSI HGG,CENTRAL,POLISSONOGRAFIA,25.0,1.0,4.00,1,0.00,24.0,4,1.0,4.17,445.00
8933,2026-10,COMPLEXO REGULADOR MUNICIPAL DE RIO VERDE,7909748 / FLAVIO VIEIRA DE FARIA,SUDOESTE I,POLISSONOGRAFIA,10.0,1.0,10.00,1,0.00,8.0,0,0.0,0.00,0.00